baseURL = "https://pdfmake.github.io/docs/"
languageCode = "en-us"
title = "pdfmake"
theme = "docdock"

[params]
editURL = "https://github.com/pdfmake/docs/edit/master/content/"
disableSearch = true

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-play'></i> Playground"
identifier = "playground"
url = "http://pdfmake.org/playground.html"
weight = 1

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-home'></i> pdfmake.org"
identifier = "pdfmakeorg"
url = "http://pdfmake.org"
weight = 2

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "github"
url = "https://github.com/bpampuch/pdfmake"
weight = 3